title: mangala's blog
author: Mangala Kodagoda
email: '&#109;&#97;&#105;&#108;.ma&#110;&#103;ala&#64;gmail.&#99;&#111;m'
description: > # this means to ignore newlines until "baseurl:"
  A software developer blogs about personal projects,
  thoughts, ideas or anything else worth recording.

twitter_username: tweetmangala
#github_username:  jekyll
#linkedin_username:    mangala81
#google_plus_username: mail.mangala
#facebook_username:    mkodagoda

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock

plugins:
  - jekyll-seo-tag
